CREATE DATABASE perfiles_db;
USE perfiles_db;

CREATE TABLE persona(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(25),
apellido VARCHAR(25),
email VARCHAR(40),
dirección VARCHAR(60),
Acercade VARCHAR(500),
imageurl VARCHAR(300),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);